import { notFound } from "next/navigation"
import { AdminPageBody, AdminPageHeader } from "@/components/admin/page-header"
import { BusinessActions } from "@/components/admin/business-actions"
import { getBusinessDetail } from "@/lib/admin/control-centre"

export const dynamic = "force-dynamic"
export default async function BusinessDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const detail = await getBusinessDetail(id); if (!detail) notFound(); const b = detail.business
  const cards = [["Plan", `${b.plan} · ${b.subscriptionStatus}`],["Widget", b.widgetStatus],["Usage", `${b.conversations} conversations`],["Knowledge", `${detail.configuration.services} services · ${detail.configuration.faqs} FAQs`],["Team", `${detail.configuration.team} members`],["AI", `${detail.ai.requests} requests · $${detail.ai.cost.toFixed(4)}`]]
  return <><AdminPageHeader title={b.name} description={`${b.ownerEmail} · Business ID ${b.id}`} generatedAt={new Date().toISOString()} /><AdminPageBody><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label,value])=><article key={label} className="rounded-xl border border-[#242830] bg-[#0E1013] p-4"><p className="text-xs text-[#858D97]">{label}</p><p className="mt-2 text-lg font-semibold capitalize text-[#EAEBED]">{value}</p></article>)}</section><section className="rounded-xl border border-[#242830] bg-[#0E1013] p-4"><h2 className="text-sm font-semibold">Controlled account action</h2><p className="mt-1 mb-4 text-xs text-[#747C86]">Pausing disables widget installations. It does not rewrite billing state or delete customer data.</p><BusinessActions id={id} paused={b.widgetStatus !== "active"} /></section><section className="grid gap-4 xl:grid-cols-2">{Object.entries(detail.recent).map(([key, rows]) => <div key={key} className="rounded-xl border border-[#242830] bg-[#0E1013] p-4"><h2 className="text-sm font-semibold capitalize">Recent {key}</h2>{rows.length ? <ul className="mt-3 divide-y divide-[#22262D]">{rows.slice(0,8).map((row)=><li key={String(row.id)} className="py-2.5 text-xs text-[#9BA2AB]"><span className="font-medium text-[#D9DCE0]">{String(row.name ?? row.visitor_name ?? row.session_id ?? row.email_type ?? row.service ?? row.id)}</span><span className="ml-2 capitalize">{String(row.status ?? "recorded")}</span></li>)}</ul> : <p className="mt-4 text-xs text-[#666E78]">No {key} recorded.</p>}</div>)}</section></AdminPageBody></>
}
