"use client"

import { useState, useTransition } from "react"
import { useRouter } from "next/navigation"
import { toast } from "sonner"
import { saveOperationsSettingsAction } from "@/app/actions/admin-control"

type Settings = { maintenance_mode?: boolean; support_contact?: string; system_announcement?: string; default_rate_limit?: number; incident_thresholds?: { ai_failures?: number; email_failures?: number; booking_failures?: number } }

export function ConfigurationForm({ initial }: { initial: Settings }) {
  const router=useRouter(); const [pending,startTransition]=useTransition(); const [maintenanceMode,setMaintenanceMode]=useState(Boolean(initial.maintenance_mode)); const [supportContact,setSupportContact]=useState(initial.support_contact??"support@aivaspa.online"); const [announcement,setAnnouncement]=useState(initial.system_announcement??""); const [rate,setRate]=useState(initial.default_rate_limit??60); const [ai,setAi]=useState(initial.incident_thresholds?.ai_failures??5); const [email,setEmail]=useState(initial.incident_thresholds?.email_failures??5); const [booking,setBooking]=useState(initial.incident_thresholds?.booking_failures??3)
  const save=()=>startTransition(async()=>{const result=await saveOperationsSettingsAction({maintenanceMode,supportContact,systemAnnouncement:announcement,defaultRateLimit:rate,aiFailureThreshold:ai,emailFailureThreshold:email,bookingFailureThreshold:booking}); if(result.ok){toast.success(result.message);router.refresh()}else toast.error(result.error)})
  const input="mt-1.5 w-full rounded-lg border border-[#2B3038] bg-[#111318] px-3 py-2 text-sm text-white outline-none focus:border-[#DDE047]"
  return <div className="space-y-4"><section className="rounded-xl border border-[#242830] bg-[#0E1013] p-4"><div className="flex items-center justify-between gap-4"><div><h2 className="text-sm font-semibold">Maintenance mode</h2><p className="mt-1 text-xs text-[#747C86]">Operational flag for controlled maintenance workflows.</p></div><button type="button" onClick={()=>setMaintenanceMode((value)=>!value)} className={`h-6 w-11 rounded-full p-1 ${maintenanceMode?"bg-[#E0E242]":"bg-[#30353D]"}`}><span className={`block size-4 rounded-full bg-[#090A0C] transition ${maintenanceMode?"translate-x-5":""}`} /></button></div></section><section className="grid gap-4 rounded-xl border border-[#242830] bg-[#0E1013] p-4 md:grid-cols-2"><label className="text-xs text-[#949BA4]">Support contact<input className={input} value={supportContact} onChange={(event)=>setSupportContact(event.target.value)} /></label><label className="text-xs text-[#949BA4]">Default requests per minute<input className={input} type="number" min={1} max={1000} value={rate} onChange={(event)=>setRate(Number(event.target.value))} /></label><label className="text-xs text-[#949BA4] md:col-span-2">System announcement<textarea className={`${input} min-h-20`} value={announcement} onChange={(event)=>setAnnouncement(event.target.value)} maxLength={500} /></label></section><section className="rounded-xl border border-[#242830] bg-[#0E1013] p-4"><h2 className="text-sm font-semibold">Incident thresholds</h2><p className="mt-1 text-xs text-[#747C86]">Minimum repeated failures before an operational incident is created.</p><div className="mt-4 grid gap-4 md:grid-cols-3"><label className="text-xs text-[#949BA4]">AI failures<input className={input} type="number" min={2} value={ai} onChange={(event)=>setAi(Number(event.target.value))} /></label><label className="text-xs text-[#949BA4]">Email failures<input className={input} type="number" min={2} value={email} onChange={(event)=>setEmail(Number(event.target.value))} /></label><label className="text-xs text-[#949BA4]">Booking failures<input className={input} type="number" min={2} value={booking} onChange={(event)=>setBooking(Number(event.target.value))} /></label></div></section><button disabled={pending} onClick={save} className="rounded-lg bg-[#E3E545] px-4 py-2.5 text-xs font-semibold text-[#090A0C]">{pending?"Saving…":"Save configuration"}</button></div>
}
