import Link from "next/link"
import { notFound } from "next/navigation"
import { AdminPageBody, AdminPageHeader } from "@/components/admin/page-header"
import { getUsersDetailed, getAuditEntries } from "@/lib/admin/control-centre"

export const dynamic = "force-dynamic"
export default async function AdminUserDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const [users, audit] = await Promise.all([getUsersDetailed(), getAuditEntries()]); const user = users.find((item) => item.id === id); if (!user) notFound(); const history = audit.filter((entry) => entry.target === id).slice(0,20)
  return <><AdminPageHeader title={user.email || "User profile"} description={`Authentication and customer association · ${user.id}`} generatedAt={new Date().toISOString()} /><AdminPageBody><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Account",user.status],["Role",user.role],["Security",user.securityStatus],["Last sign-in",user.lastSignInAt ? new Date(user.lastSignInAt).toLocaleString() : "Never"]].map(([label,value])=><article key={label} className="rounded-xl border border-[#242830] bg-[#0E1013] p-4"><p className="text-xs text-[#858D97]">{label}</p><p className="mt-2 text-sm font-semibold capitalize text-[#EAEBED]">{value}</p></article>)}</section><section className="rounded-xl border border-[#242830] bg-[#0E1013] p-4"><h2 className="text-sm font-semibold">Business association</h2>{user.businessId ? <Link className="mt-3 inline-block text-sm text-[#E2E445]" href={`/admin/businesses/${user.businessId}`}>{user.business} · {user.plan}</Link> : <p className="mt-3 text-xs text-[#6D7580]">This user is not associated with an active business record.</p>}</section><section className="rounded-xl border border-[#242830] bg-[#0E1013] p-4"><h2 className="text-sm font-semibold">Audit history</h2>{history.length ? <ul className="mt-3 divide-y divide-[#22262D]">{history.map((entry)=><li key={entry.id} className="py-2.5 text-xs"><span className="text-[#D7DADE]">{entry.action}</span><span className="ml-2 text-[#6D7580]">{new Date(entry.time).toLocaleString()}</span></li>)}</ul> : <p className="mt-3 text-xs text-[#6D7580]">No sensitive admin actions recorded for this user.</p>}</section></AdminPageBody></>
}
