import { AdminPageBody, AdminPageHeader } from "@/components/admin/page-header"
import { getSubscriptions } from "@/lib/admin/control-centre"

export const dynamic = "force-dynamic"
export default async function ConversationUsagePage() {
  const rows = await getSubscriptions()
  const total = rows.reduce((sum, row) => sum + Number(row.conversations_used ?? 0), 0)
  return <><AdminPageHeader title="Conversation usage" description="Billable production visitor conversations by subscription period." generatedAt={new Date().toISOString()} /><AdminPageBody><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article className="rounded-xl border border-[#242830] bg-[#0E1013] p-4"><p className="text-xs text-[#8D949E]">Metered conversations</p><p className="mt-3 text-3xl font-semibold">{total.toLocaleString()}</p><p className="mt-2 text-[11px] text-[#666E78]">Current subscription periods</p></article><article className="rounded-xl border border-[#242830] bg-[#0E1013] p-4"><p className="text-xs text-[#8D949E]">Businesses metered</p><p className="mt-3 text-3xl font-semibold">{rows.length}</p><p className="mt-2 text-[11px] text-[#666E78]">Idempotent usage counters</p></article></section><div className="overflow-x-auto rounded-xl border border-[#242830] bg-[#0E1013]"><table className="w-full text-xs"><thead className="text-left text-[10px] uppercase tracking-wide text-[#626A74]"><tr><th className="px-4 py-3">Business</th><th>Plan</th><th>Used</th><th>Limit</th><th>Utilisation</th><th>Period ends</th></tr></thead><tbody className="divide-y divide-[#22262D]">{rows.map((row) => { const used=Number(row.conversations_used??0), limit=Number(row.monthly_quota??0), pct=limit?Math.min(100,used/limit*100):0; return <tr key={String(row.id)}><td className="px-4 py-3 font-medium text-[#E1E3E6]">{String(row.business)}</td><td className="capitalize">{String(row.plan)}</td><td>{used.toLocaleString()}</td><td>{limit.toLocaleString()}</td><td className="min-w-40 pr-4"><div className="h-2 rounded-full bg-[#20242A]"><div className="h-full rounded-full bg-[#DDE047]" style={{width:`${pct}%`}} /></div><p className="mt-1 text-[10px] text-[#68707A]">{pct.toFixed(1)}%</p></td><td>{new Date(String(row.period_end)).toLocaleDateString()}</td></tr>})}</tbody></table></div></AdminPageBody></>
}
